spring:
  application:
    name: spring-security
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:7000/spring-security
    username: DB_USERNAME
    password: DB_PASSWORD
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 9091 
